#!/usr/bin/env node
/**
 * Extracts the design-token blocks out of a stylesheet into data/theme.json.
 *
 * WHY this is a script and not a hand-transcription: the legacy globals.css
 * defined ~45 custom properties across two blocks. Retyping them is exactly
 * the kind of bulk work that silently introduces a wrong hex digit, and a
 * wrong hex digit in a token is invisible until someone notices the shade is
 * off. Parsing the original guarantees the JSON is byte-faithful.
 *
 * It also emits tests/fixtures/legacy-theme.css, a verbatim copy of the two
 * source blocks, so the regeneration test has something to diff against that
 * was never touched by a human either.
 *
 * Usage: node scripts/extract-theme.mjs [source.css]
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname, resolve } from 'node:path'

const SOURCE = resolve(process.argv[2] ?? 'app/globals.css')

/**
 * Pulls the body of the first rule whose selector matches exactly.
 * Deliberately naive: these blocks contain no nested braces, so a scan to the
 * first `}` is correct and avoids pulling in a CSS parser dependency.
 */
function readBlock(css, selector) {
  const start = css.indexOf(selector)
  if (start === -1) throw new Error(`selector not found: ${selector}`)
  const open = css.indexOf('{', start)
  const close = css.indexOf('}', open)
  if (open === -1 || close === -1) throw new Error(`unterminated block: ${selector}`)
  return { body: css.slice(open + 1, close), raw: css.slice(start, close + 1) }
}

/** Parses `--name: value;` declarations, preserving source order. */
function parseTokens(body) {
  const tokens = {}
  for (const line of body.split(';')) {
    const text = line.replace(/\/\*[\s\S]*?\*\//g, '').trim()
    if (!text.startsWith('--')) continue
    const colon = text.indexOf(':')
    if (colon === -1) continue
    tokens[text.slice(0, colon).trim()] = text.slice(colon + 1).trim()
  }
  return tokens
}

const css = readFileSync(SOURCE, 'utf8')
const root = readBlock(css, ':root')
const dark = readBlock(css, '.dark')

const theme = {
  $comment:
    'Design tokens rendered into CSS custom properties at runtime. "light" defines :root, "dark" is the .dark override. Generated by scripts/extract-theme.mjs.',
  light: parseTokens(root.body),
  dark: parseTokens(dark.body),
}

writeFileSync('data/theme.json', `${JSON.stringify(theme, null, 2)}\n`)

const fixture = 'tests/fixtures/legacy-theme.css'
mkdirSync(dirname(fixture), { recursive: true })
writeFileSync(fixture, `${root.raw}\n\n${dark.raw}\n`)

console.log(
  `extracted ${Object.keys(theme.light).length} light + ${Object.keys(theme.dark).length} dark tokens`
)
